Version 4
SymbolType CELL
WINDOW 0 56 32 Left 2
WINDOW 3 56 72 Left 2
SYMATTR Value PMOS
SYMATTR Prefix MP
SYMATTR Description P-channel MOSFET with bulk terminal
PIN 48 0 NONE 8
PINATTR PinName D
PINATTR SpiceOrder 1
PIN 0 80 NONE 8
PINATTR PinName G
PINATTR SpiceOrder 2
PIN 48 96 NONE 8
PINATTR PinName S
PINATTR SpiceOrder 3
PIN 48 48 NONE 8
PINATTR PinName B
PINATTR SpiceOrder 4
