Version 4
SymbolType CELL
WINDOW 0 56 32 Left 2
WINDOW 3 56 68 Left 2
SYMATTR Value PNP
SYMATTR Prefix QP
SYMATTR Description PNP bipolar transistor
PIN 64 0 NONE 8
PINATTR PinName C
PINATTR SpiceOrder 1
PIN 0 48 NONE 8
PINATTR PinName B
PINATTR SpiceOrder 2
PIN 64 96 NONE 8
PINATTR PinName E
PINATTR SpiceOrder 3
