Version 4
SymbolType CELL
WINDOW 0 24 16 Left 2
WINDOW 3 24 96 Left 2
SYMATTR Value SW
SYMATTR Prefix S
SYMATTR Description Voltage-controlled switch
PIN 0 16 NONE 8
PINATTR PinName A
PINATTR SpiceOrder 1
PIN 0 96 NONE 8
PINATTR PinName B
PINATTR SpiceOrder 2
PIN -48 80 NONE 8
PINATTR PinName NC+
PINATTR SpiceOrder 3
PIN -48 32 NONE 8
PINATTR PinName NC-
PINATTR SpiceOrder 4
